spring:
  dubbo:
    application:
      name: spring-boot-dubbo-provider
    registry:
      address: zookeeper://localhost:2181
    protocol:
      name: dubbo
      port: 20880
    scan: org.xueliang.spring.boot.dubbo